import { h, renderToString, type HtmlChild } from "./html.js"
import {
  patchElements,
  patchSignals,
  type PatchElementsNamespace,
  type PatchElementsMode,
  type PatchElementsOptions,
  type PatchSignalsOptions,
  type SignalState
} from "./sse.js"

/**
 * Safe network configuration for Datastar action helpers.
 *
 * @remarks
 * Datastar action helpers own their protocol status codes, so `status` and `statusText` are not
 * accepted here. Use `reply.page()` or a plain `Response` for ordinary HTTP status semantics.
 */
export type StreamResponseInit = Omit<ResponseInit, "status" | "statusText">

/**
 * Options for the full HTML document generated by `reply.page()`.
 */
export interface PageOptions {
  /** Language rendered on the root `<html>` element. @defaultValue `"en"` */
  readonly lang?: string
  /** Children rendered into the document `<head>`. */
  readonly head?: HtmlChild | readonly HtmlChild[]
  /** Optional document title rendered before additional head children. */
  readonly title?: string
}

/**
 * Options for periodic SSE comment heartbeats in `reply.stream()`.
 */
export interface SseHeartbeatOptions {
  /** Interval between heartbeat comments in milliseconds. @defaultValue `15000` */
  readonly intervalMs?: number
  /** Delay before the first heartbeat comment in milliseconds. Defaults to `intervalMs`. */
  readonly initialDelayMs?: number
  /** Comment text sent after the SSE `:` heartbeat prefix. @defaultValue `"heartbeat"` */
  readonly comment?: string
}

/**
 * Element patch options for `reply.patch()`.
 */
export interface PatchOptions extends PatchElementsOptions {}

/**
 * Signal patch options for `reply.signals()`.
 */
export interface SignalsOptions extends PatchSignalsOptions {}

/**
 * SSE stream options for `reply.stream()`.
 */
export interface SseStreamOptions {
  /** Optional heartbeat comments that keep long-lived SSE streams active. */
  readonly heartbeat?: SseHeartbeatOptions
}

/**
 * Direct HTML response options.
 */
export interface DirectHtmlOptions {
  /** CSS selector for target elements when Datastar handles a direct HTML response. */
  readonly selector?: string
  /** Patch operation used for the direct HTML response. */
  readonly mergeMode?: PatchElementsMode
  /** Markup namespace used to parse the direct HTML response. */
  readonly elementNamespace?: PatchElementsNamespace
  /** Whether Datastar should use the View Transition API when applying the direct patch. */
  readonly useViewTransition?: boolean
}

/**
 * Direct signal response options.
 */
export interface DirectSignalsOptions {
  /** Whether signal keys should only be patched when they do not already exist. */
  readonly onlyIfMissing?: boolean
}

/**
 * Direct script response options.
 */
export interface DirectScriptOptions {
  /** Attributes Datastar applies to the generated `<script>` element. */
  readonly attributes?: Readonly<Record<string, string | number | boolean>>
}

/**
 * Safe navigation response options.
 */
export interface NavigateOptions extends DirectScriptOptions {
  /** Base URL used to resolve relative navigation targets. @defaultValue `"http://localhost"` */
  readonly baseUrl?: string | URL
  /** Additional absolute origins allowed for cross-origin navigation. */
  readonly allowedOrigins?: readonly (string | URL)[]
}

/**
 * A framed SSE string chunk that can be written to an SSE stream.
 */
export interface SseChunk {
  /** Fully framed SSE event content. */
  readonly content: string
}

/**
 * Raw chunk values accepted while adapting iterables into an SSE stream.
 */
type SseChunkInput = string | SseChunk | Uint8Array

/**
 * Input accepted by `reply.stream()` for Datastar SSE responses.
 */
export type SseStreamInput =
  | string
  | SseChunk
  | Iterable<SseChunkInput>
  | AsyncIterable<SseChunkInput>
  | ReadableStream<SseChunkInput>

/**
 * Error thrown when `reply.navigate()` rejects an unsafe navigation target.
 */
export class NavigationUrlError extends Error {
  /**
   * @param url The unsafe URL input that was rejected.
   */
  constructor(readonly url: string) {
    super(`Unsafe navigation URL: ${JSON.stringify(url)}`)
  }
}

/** Shared encoder instance avoids allocating per stream chunk. */
const textEncoder = new TextEncoder()

/** Timer type that works in both DOM and Node type environments. */
type Timer = ReturnType<typeof setTimeout>

/**
 * Merges caller headers over protocol defaults without losing default content types.
 */
const mergeHeaders = (defaults: HeadersInit, headers: HeadersInit | undefined): Headers => {
  const merged = new Headers(defaults)
  new Headers(headers).forEach((value, key) => {
    merged.set(key, value)
  })
  return merged
}

/**
 * Creates a Datastar action response while preserving SDK-owned status semantics.
 */
const response = (
  body: BodyInit | null,
  init: StreamResponseInit | undefined,
  status: 200 | 204,
  defaultHeaders: HeadersInit = {}
): Response =>
  new Response(body, {
    status,
    headers: mergeHeaders(defaultHeaders, init?.headers)
  })

/** Default headers required for Datastar SSE responses. */
const sseHeaders = {
  "cache-control": "no-cache",
  "content-type": "text/event-stream"
} as const

/**
 * Normalizes optional singular/plural child inputs into a renderable array.
 */
const childrenArray = (child: HtmlChild | readonly HtmlChild[] | undefined): readonly HtmlChild[] => {
  if (child === undefined) {
    return []
  }
  return Array.isArray(child) ? child : [child]
}

/**
 * Renders the full document shell used by `reply.page()`.
 */
const htmlDocument = (body: HtmlChild | readonly HtmlChild[], options: PageOptions): string =>
  `<!doctype html>${renderToString(
    h(
      "html",
      { lang: options.lang ?? "en" },
      h("head", {}, options.title === undefined ? null : h("title", {}, options.title), ...childrenArray(options.head)),
      h("body", {}, ...childrenArray(body))
    )
  )}`

/**
 * Adapts all supported stream input forms into one async iteration path.
 */
const normalizeSseChunk = (chunk: SseChunkInput): string | Uint8Array =>
  typeof chunk === "object" && !(chunk instanceof Uint8Array) ? chunk.content : chunk

async function* toAsyncIterable(source: SseStreamInput): AsyncIterable<string | Uint8Array> {
  if (typeof source === "string") {
    yield source
    return
  }

  if (typeof source === "object" && source !== null && "content" in source) {
    yield source.content
    return
  }

  if (typeof source === "object" && source !== null && "getReader" in source) {
    const reader = source.getReader()
    try {
      while (true) {
        const result = await reader.read()
        if (result.done) return
        yield normalizeSseChunk(result.value)
      }
    } finally {
      reader.releaseLock()
    }
    return
  }

  if (typeof source === "object" && source !== null && Symbol.asyncIterator in source) {
    for await (const chunk of source as AsyncIterable<SseChunkInput>) {
      yield normalizeSseChunk(chunk)
    }
    return
  }

  for (const chunk of source) {
    yield normalizeSseChunk(chunk)
  }
}

/**
 * Encodes an SSE comment heartbeat without creating a Datastar event.
 */
const sseComment = (comment = ""): string =>
  comment.length === 0 ? ":\n\n" : `: ${comment.replaceAll("\n", "\n: ")}\n\n`

/**
 * Converts string chunks to bytes while preserving already-encoded chunks.
 */
const encodeChunk = (chunk: string | Uint8Array): Uint8Array =>
  typeof chunk === "string" ? textEncoder.encode(chunk) : chunk

/**
 * Bridges async event chunks into a backpressure-aware Web `ReadableStream`.
 */
const readableStreamFrom = (
  source: AsyncIterable<string | Uint8Array>,
  heartbeat?: SseHeartbeatOptions
): ReadableStream<Uint8Array> => {
  const iterator = source[Symbol.asyncIterator]()
  let closed = false
  let started = false
  let initial: Timer | undefined
  let interval: Timer | undefined

  const cleanup = () => {
    closed = true
    clearTimeout(initial)
    clearInterval(interval)
  }

  return new ReadableStream({
    async pull(controller) {
      if (heartbeat !== undefined && !started) {
        started = true
        const comment = sseComment(heartbeat.comment ?? "heartbeat")
        const intervalMs = heartbeat.intervalMs ?? 15_000
        const tick = () => {
          if (!closed && (controller.desiredSize ?? 0) > 0) controller.enqueue(encodeChunk(comment))
        }
        initial = setTimeout(() => {
          initial = undefined
          tick()
          if (!closed) interval = setInterval(tick, intervalMs)
        }, heartbeat.initialDelayMs ?? intervalMs)
      }

      try {
        const result = await iterator.next()
        if (closed) return
        if (result.done === true) {
          cleanup()
          controller.close()
          return
        }
        controller.enqueue(encodeChunk(result.value))
      } catch (error) {
        cleanup()
        throw error
      }
    },
    cancel() {
      cleanup()
      void iterator.return?.()
    }
  })
}

/**
 * Creates a full HTML document response.
 *
 * @param body Children rendered inside the document `<body>`.
 * @param options Document rendering options.
 * @param init Native response options such as `status` and `headers`.
 * @returns A native HTML `Response`.
 */
export const page = (
  body: HtmlChild | readonly HtmlChild[],
  options: PageOptions = {},
  init: ResponseInit = {}
): Response =>
  new Response(htmlDocument(body, options), {
    ...init,
    headers: mergeHeaders({ "content-type": "text/html; charset=utf-8" }, init.headers)
  })

/**
 * Creates a Datastar SSE element patch response.
 *
 * @param elements HTML child tree to patch into the browser document.
 * @param options Datastar patch options.
 * @param init Native response options excluding status fields.
 * @returns A `200` SSE `Response` containing one patch-elements event.
 */
export const patch = (
  elements: HtmlChild,
  options: PatchOptions = {},
  init: StreamResponseInit = {}
): Response =>
  response(patchElements(renderToString(elements), options), init, 200, sseHeaders)

/**
 * Creates a Datastar SSE signal patch response.
 *
 * @param value Signal state or a pre-encoded signal patch string.
 * @param options Datastar signal patch options.
 * @param init Native response options excluding status fields.
 * @returns A `200` SSE `Response` containing one patch-signals event.
 */
export const signals = (
  value: SignalState | string,
  options: SignalsOptions = {},
  init: StreamResponseInit = {}
): Response =>
  response(patchSignals(value, options), init, 200, sseHeaders)

/**
 * Creates a Datastar SSE stream response from event chunks.
 *
 * @param events Event chunks, iterables, async iterables, or a readable stream.
 * @param options SSE stream options.
 * @param init Native response options excluding status fields.
 * @returns A `200` SSE streaming `Response`.
 */
export const stream = (
  events: SseStreamInput,
  options: SseStreamOptions = {},
  init: StreamResponseInit = {}
): Response => {
  const { heartbeat } = options
  return response(readableStreamFrom(toAsyncIterable(events), heartbeat), init, 200, sseHeaders)
}

/**
 * Creates a Datastar command-completion response with no body.
 *
 * @param init Native response options excluding status fields.
 * @returns A `204` no-content `Response`.
 */
export const done = (init: StreamResponseInit = {}): Response =>
  response(null, init, 204)

/**
 * Creates a Datastar direct HTML response.
 *
 * @remarks
 * Prefer `reply.patch()` for normal Datastar updates. Direct HTML responses are public escape
 * hatches for integrations that specifically need Datastar's direct-response handling.
 *
 * @param html HTML child tree to send as a direct response.
 * @param options Direct HTML response options.
 * @param init Native response options excluding status fields.
 * @returns A `200` direct HTML `Response`.
 */
export const directHtml = (
  html: HtmlChild,
  options: DirectHtmlOptions = {},
  init: StreamResponseInit = {}
): Response => {
  const { selector, mergeMode, elementNamespace, useViewTransition } = options
  return response(renderToString(html), init, 200, {
    "content-type": "text/html; charset=utf-8",
    ...(selector === undefined ? {} : { "datastar-selector": selector }),
    ...(mergeMode === undefined ? {} : { "datastar-mode": mergeMode }),
    ...(elementNamespace === undefined ? {} : { "datastar-namespace": elementNamespace }),
    ...(useViewTransition === undefined ? {} : { "datastar-use-view-transition": String(useViewTransition) })
  })
}

/**
 * Creates a Datastar direct signal response.
 *
 * @remarks
 * Prefer `reply.signals()` for normal Datastar signal patches. Direct signal responses are public
 * escape hatches for integrations that specifically need Datastar's direct-response handling.
 *
 * @param value Signal state or a pre-encoded signal patch string.
 * @param options Direct signal response options.
 * @param init Native response options excluding status fields.
 * @returns A `200` direct JSON `Response`.
 */
export const directSignals = (
  value: SignalState | string,
  options: DirectSignalsOptions = {},
  init: StreamResponseInit = {}
): Response => {
  const { onlyIfMissing } = options
  return response(typeof value === "string" ? value : JSON.stringify(value), init, 200, {
    "content-type": "application/json; charset=utf-8",
    ...(onlyIfMissing === undefined ? {} : { "datastar-only-if-missing": String(onlyIfMissing) })
  })
}

/**
 * Creates a Datastar direct script response.
 *
 * @remarks
 * This is a trust-boundary escape hatch. Only pass JavaScript produced by trusted application code.
 * Prefer `reply.navigate()` for navigation and structured patches for ordinary UI updates.
 *
 * @param script JavaScript source to execute in the browser.
 * @param options Direct script response options.
 * @param init Native response options excluding status fields.
 * @returns A `200` direct JavaScript `Response`.
 */
export const directScript = (
  script: string,
  options: DirectScriptOptions = {},
  init: StreamResponseInit = {}
): Response => {
  const { attributes } = options
  return response(script, init, 200, {
    "content-type": "text/javascript; charset=utf-8",
    ...(attributes === undefined ? {} : { "datastar-script-attributes": JSON.stringify(attributes) })
  })
}

/**
 * Normalizes navigation targets and rejects cross-origin or non-HTTP(S) URLs by default.
 */
const safeNavigationUrl = (
  input: string | URL,
  options: {
    readonly baseUrl?: string | URL | undefined
    readonly allowedOrigins?: readonly (string | URL)[] | undefined
  } = {}
): string => {
  const raw = input.toString()
  if (/[\u0000-\u001F\u007F]/u.test(raw)) {
    throw new NavigationUrlError(raw)
  }

  let base: URL
  let url: URL
  try {
    base = new URL(options.baseUrl?.toString() ?? "http://localhost")
    url = new URL(raw, base)
  } catch {
    throw new NavigationUrlError(raw)
  }

  if (url.protocol !== "http:" && url.protocol !== "https:") {
    throw new NavigationUrlError(raw)
  }

  if (url.origin === base.origin) {
    return `${url.pathname}${url.search}${url.hash}`
  }

  for (const origin of options.allowedOrigins ?? []) {
    try {
      const allowed = new URL(origin.toString())
      if ((allowed.protocol === "http:" || allowed.protocol === "https:") && allowed.origin === url.origin) {
        return url.toString()
      }
    } catch {
      // Treat malformed allowlist entries as non-matches.
    }
  }

  throw new NavigationUrlError(raw)
}

/**
 * Creates a safe Datastar direct script response that navigates the browser.
 *
 * @param url Relative or allowlisted absolute URL to navigate to.
 * @param options Navigation and script options.
 * @param init Native response options excluding status fields.
 * @returns A `200` direct JavaScript `Response` that assigns `window.location.href`.
 * @throws {@link NavigationUrlError} When the URL is malformed, non-HTTP(S), or cross-origin without being allowlisted.
 */
export const navigate = (
  url: string | URL,
  options: NavigateOptions = {},
  init: StreamResponseInit = {}
): Response => {
  const { baseUrl, allowedOrigins, ...scriptOptions } = options
  const safeUrl = safeNavigationUrl(url, { baseUrl, allowedOrigins })
  return directScript(`window.location.href = ${JSON.stringify(safeUrl)}`, scriptOptions, init)
}
